# 模型配置
model:
  image_size: 128
  in_channels: 3
  out_channels: 3
  base_channels: 128
  time_emb_dim: 512
  audio_dim: 1024
  face_dim: 1024
  num_heads: 8
  num_layers: 4
  diffusion_steps: 1000
  pretrained_path: "pretrained/latent_sync_model.pth"  # 预训练模型路径

# 训练配置
training:
  batch_size: 16
  learning_rate: 2e-5
  weight_decay: 1e-4
  epochs: 100
  clip_grad_norm: 1.0
  sync_loss_weight: 0.5
  temporal_loss_weight: 0.3
  log_interval: 10
  save_interval: 5

# 推理配置
inference:
  num_steps: 50  # 推理时的扩散步数（小于训练步数可加速）
  guidance_scale: 3.0  # 引导尺度，值越大条件影响越强

# 数据配置
data:
  root: "dataset"  # 数据集根目录
  audio_sample_rate: 16000
  n_mfcc: 128
  video_fps: 25
  max_sequence_length: 128
  num_workers: 4  # 数据加载线程数
  train_val_split: 0.8  # 训练集比例
    